apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  labels:
    name: portfolio
spec:
  replicas: 1
  selector:
    matchlabels:
      name: portfolio
  template:
    metadata:
      labels:
        name: portfolio
    spec:
      containers:
      - name: portfolio
        imgae: karthickdocker28/goapp:v1
        ports:
        - containerPort: 8080
