apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  labels:
    name: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      name: portfolio
  template:
    metadata:
      labels:
        name: portfolio
    spec:
      containers:
      - name: portfolio
        image: karthickdocker28/go-web-app:10330758609
        ports:
        - containerPort: 8080
