apiVersion: v1
kind: Service
metadata:
  name: portfolio
  labels:
    name: portfolio
spec:
  type: ClusterIP
  selector:
    name: portfolio
  ports:
    Port: 80
    targetPort: 8080
    protocol: TCP
